debug:
  draw_icons: true
  draw_traj_set: false
  multiproc: false
  save_plots: true
  show_plots: false
general:
  path_scenarios: "../cvae/scenarios_v2"
planning:
  dt: 0.1
  replanning_frequency: 1
  time_steps_computation: 50
sampling:
  t_min: 0.2
  cvae_sampling: true
  z_dim: 32
  c_dim: 518
  num_samples: 100
  cvae_model_path: "../cvae/model/weights/cvae_model_lr_0.001_batch_512_epochs_5_zdim_32.pth"
vehicle:
  id_type_vehicle: 2
